namespace Qspace.pdqb

/-- The finite set of fundamental chiral states. -/
abbrev FundamentalState := Fin 8

/-- Projection into fundamental chiral state space. -/
def projectFundamental (n : Nat) : FundamentalState :=
  ⟨n % 8, Nat.mod_lt n (by decide)⟩

/-- Every fundamental state is generated by projection. -/
theorem fundamental_complete (s : FundamentalState) :
  ∃ n : Nat, projectFundamental n = s := by
  refine ⟨s.val, ?_⟩
  cases s with
  | mk val isLt =>
      simp [projectFundamental, Nat.mod_eq_of_lt isLt]

/-- Generation by first eight values. -/
theorem first_eight_generate_all (s : FundamentalState) :
  ∃ n : Nat, n < 8 ∧ projectFundamental n = s := by
  refine ⟨s.val, s.isLt, ?_⟩
  cases s with
  | mk val isLt =>
      simp [projectFundamental, Nat.mod_eq_of_lt isLt]

/-- Distinctness of first eight residues. -/
theorem first_eight_distinct (i j : Nat) (hi : i < 8) (hj : j < 8)
  (h : projectFundamental i = projectFundamental j) :
  i = j := by
  have hv := congrArg Fin.val h
  simpa [projectFundamental, Nat.mod_eq_of_lt hi, Nat.mod_eq_of_lt hj] using hv

end Qspace.pdqb
