import Qspace.pdqb.ProjectionCore

namespace Qspace.pdqb

/--
Pell channel:
constant torsional increment 2.
This is the minimal rational Pell-style projection channel.
-/
def pellDeltas (n : Nat) : List Nat :=
  List.replicate n 2

/--
Projected Pell trace in the fundamental chiral state space.
-/
def pellProjectedTrace (start n : Nat) : List FundamentalState :=
  projectedChirality start (pellDeltas n)

/--
Displayed Pell trace, using 8 instead of 0 at cycle completion.
-/
def pellDisplayTrace (start n : Nat) : List Nat :=
  (pellProjectedTrace start n).map (fun s => displayChirality s.val)

/--
The Pell trace is a projected trace of an underlying substrate progression.
-/
theorem pell_projection_exists (start n : Nat) :
  ∃ trace : List FundamentalState, IsProjectedTrace start (pellDeltas n) trace := by
  exact projected_trace_exists start (pellDeltas n)

/--
The Pell channel is generated by constant torsion 2.
-/
theorem pell_channel_constant (n : Nat) :
  pellDeltas n = List.replicate n 2 := by
  rfl

end Qspace.pdqb
