import Qspace.pdqb.ProjectionCore

namespace Qspace.pdqb

/--
Phi channel:
constant torsional increment 1.
This is the minimal rational Phi-style projection channel.
-/
def phiDeltas (n : Nat) : List Nat :=
  List.replicate n 1

/--
Projected Phi trace in the fundamental chiral state space.
-/
def phiProjectedTrace (start n : Nat) : List FundamentalState :=
  projectedChirality start (phiDeltas n)

/--
Displayed Phi trace, using 8 instead of 0 at cycle completion.
-/
def phiDisplayTrace (start n : Nat) : List Nat :=
  (phiProjectedTrace start n).map (fun s => displayChirality s.val)

/--
The Phi trace is a projected trace of an underlying substrate progression.
-/
theorem phi_projection_exists (start n : Nat) :
  ∃ trace : List FundamentalState, IsProjectedTrace start (phiDeltas n) trace := by
  exact projected_trace_exists start (phiDeltas n)

/--
The Phi channel is generated by constant torsion 1.
-/
theorem phi_channel_constant (n : Nat) :
  phiDeltas n = List.replicate n 1 := by
  rfl

end Qspace.pdqb
